import { useQuery } from '@tanstack/react-query';
import { Link } from 'react-router-dom';
import { supabase } from '@/integrations/supabase/client';
import { formatMoney } from '@/lib/ads';
import { Button } from '@/components/ui/button';
type Metrics = { revenue_cents: number; order_count: number; units_sold: number; views: number; awaiting_fulfilment: number; low_stock: { variant_id: string; label: string; stock: number }[]; top_products: { product_id: string; name: string; units_sold: number; revenue_cents: number }[] };
export function CommerceOverview({ businessId }: { businessId: string }) {
  const { data, error, isLoading, refetch } = useQuery({ queryKey: ['commerce-metrics',businessId], queryFn: async () => { const { data,error } = await supabase.rpc('get_marketplace_business_metrics',{p_business_id:businessId}); if(error) throw error; return data as unknown as Metrics; } });
  return <section className="mb-6 space-y-4 border-b pb-6"><div className="flex items-center justify-between"><h2 className="text-lg font-bold">Commerce · last 30 days</h2><Link className="text-sm text-primary" to="/b?tab=orders">View orders</Link></div>{isLoading ? <p role="status">Loading sales…</p> : error ? <Button variant="outline" onClick={() => void refetch()}>Retry commerce overview</Button> : data && <><dl className="grid grid-cols-2 gap-6 sm:grid-cols-4">{[['Sales',formatMoney(data.revenue_cents)],['Paid orders',data.order_count],['Product views',data.views],['To fulfill',data.awaiting_fulfilment]].map(([label,value]) => <div key={label}><dt className="text-xs text-muted-foreground">{label}</dt><dd className="mt-2 text-2xl font-semibold tabular-nums">{value}</dd></div>)}</dl>{!!data.low_stock.length && <div className="border-t pt-4"><h3 className="text-sm font-semibold">Low inventory</h3><ul className="mt-2 space-y-2">{data.low_stock.map(v => <li key={v.variant_id} className="flex justify-between text-sm"><span>{v.label}</span><span className="text-muted-foreground">{v.stock} left</span></li>)}</ul></div>}{!!data.top_products.length && <div className="overflow-x-auto"><table className="w-full text-left text-sm"><thead><tr className="border-b text-xs text-muted-foreground"><th className="py-2">Product</th><th>Units sold</th><th className="text-right">Sales</th></tr></thead><tbody>{data.top_products.map(p => <tr key={p.product_id} className="border-b"><td className="py-3">{p.name}</td><td>{p.units_sold}</td><td className="text-right">{formatMoney(p.revenue_cents)}</td></tr>)}</tbody></table></div>}</>}</section>;
}
